### ISSUE TITLE
No captive portal on Android

### ISSUE THREAD

**Issue by cakebread** [OpenAgInitiative/python-wifi-connect#14]
I am able to reach the UI by using the IP address, but I don't get any captive portal.
Checking the output, I can see http_server.py was generating a 404 for /generate_204 instead of a 301 redirect.

This code fixes it for me:

```
            if '/generate_204' == self.path:
                self.send_response(301) # redirect
                new_path = f'http://{self.address}/'
                print(f'redirecting to {new_path}')
                self.send_header('Location', new_path)
                self.end_headers()
```

I'll be happy to submit a PR, but I am unable to test it on IOS at the moment, so I'm not sure if this breaks anything for Apple devices.

**Comment by srmoore** [comment]
If you submit a PR, I can pull it down onto a Pi here and try it out on iOS. Thanks!

**Comment by dmasinelli** [comment]
I confirm that it also works on IOS tested on Raspberry Compute Module 3

**Comment by srmoore** [comment]
Nice! Thanks @dmasinelli .
@cakebread , please submit a PR and I'll get it merged in. Thanks for catching this!
