### ISSUE TITLE
Ask balena.io to review this project

### ISSUE THREAD

**Issue by rbaynes** [OpenAgInitiative/python-wifi-connect#3]
Submitted issue to their project to ask them to review:

https://github.com/balena-io/wifi-connect/issues/289

**Comment by majorz** [comment]
You did some awesome work in making a Python spin off of wifi-connect. I spotted your issue a while ago, but was really swamped with other issues and just got the chance to get back to wifi-connect issues and look at your application.

I went through all the sources and everything looks good there.

It is a solid base for people who know Python and would like to experiment more and add custom features. Great job!

**Comment by rbaynes** [comment]
Thanks!

-rob
